export const mockOffer = {
  bedrooms: 1,
  city: { name: 'Paris', location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 } },
  description: 'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
  goods: ['Laptop friendly workspace', 'Air conditioning', 'Washer', 'Breakfast'],
  host: { id: 25, name: 'Angelina', isPro: true, avatarUrl: 'img/avatar-angelina.jpg' },
  id: 2,
  images: ['https://9.react.pages.academy/static/hotel/20.jpg',
    'https://9.react.pages.academy/static/hotel/2.jpg',
    'https://9.react.pages.academy/static/hotel/13.jpg',
    'https://9.react.pages.academy/static/hotel/3.jpg',
    'https://9.react.pages.academy/static/hotel/6.jpg',
    'https://9.react.pages.academy/static/hotel/5.jpg',
    'https://9.react.pages.academy/static/hotel/8.jpg',
    'https://9.react.pages.academy/static/hotel/1.jpg',
    'https://9.react.pages.academy/static/hotel/7.jpg',
    'https://9.react.pages.academy/static/hotel/4.jpg',
    'https://9.react.pages.academy/static/hotel/9.jpg',
    'https://9.react.pages.academy/static/hotel/15.jpg',
    'https://9.react.pages.academy/static/hotel/11.jpg',
    'https://9.react.pages.academy/static/hotel/10.jpg'],
  isFavorite: false,
  isPremium: false,
  location: { latitude: 53.563341, longitude: 9.975654, zoom: 16 },
  maxAdults: 3,
  previewImage: 'https://9.react.pages.academy/static/hotel/19.jpg',
  price: 151,
  rating: 4.3,
  title: 'Waterfront with extraordinary view',
  type: 'room',
};

export const mockOfferFavorite = {
  bedrooms: 1,
  city: { name: 'Paris', location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 } },
  description: 'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
  goods: ['Laptop friendly workspace', 'Air conditioning', 'Washer', 'Breakfast'],
  host: { id: 25, name: 'Angelina', isPro: true, avatarUrl: 'img/avatar-angelina.jpg' },
  id: 2,
  images: ['https://9.react.pages.academy/static/hotel/20.jpg',
    'https://9.react.pages.academy/static/hotel/2.jpg',
    'https://9.react.pages.academy/static/hotel/13.jpg',
    'https://9.react.pages.academy/static/hotel/3.jpg',
    'https://9.react.pages.academy/static/hotel/6.jpg',
    'https://9.react.pages.academy/static/hotel/5.jpg',
    'https://9.react.pages.academy/static/hotel/8.jpg',
    'https://9.react.pages.academy/static/hotel/1.jpg',
    'https://9.react.pages.academy/static/hotel/7.jpg',
    'https://9.react.pages.academy/static/hotel/4.jpg',
    'https://9.react.pages.academy/static/hotel/9.jpg',
    'https://9.react.pages.academy/static/hotel/15.jpg',
    'https://9.react.pages.academy/static/hotel/11.jpg',
    'https://9.react.pages.academy/static/hotel/10.jpg'],
  isFavorite: true,
  isPremium: false,
  location: { latitude: 53.563341, longitude: 9.975654, zoom: 16 },
  maxAdults: 3,
  previewImage: 'https://9.react.pages.academy/static/hotel/19.jpg',
  price: 151,
  rating: 4.3,
  title: 'Waterfront with extraordinary view',
  type: 'room',
};
